[server]
port = 1984

[aircraft]
seed = 0
count = 10                 # probability for each cell to have a aircraft
minResponse = 100          # milliseconds
maxResponse = 100          # milliseconds
minDistance = 100000          # meters
maxDistance = 100000         # meters